schema_version = "1.0.0"

id = "bobj_keyframes"
version = "0.1.1"
name = "BOBJ keyframes"
tagline = "Export actions (animation keyframes) into a .bobj file"
maintainer = "McHorse <mchorselessrider@gmail.com>"
type = "add-on"

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2020-2026 McHorse",
]
